settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
    - id: petiteinparis-com
    name: petiteinparis.com
    url: 'https://petiteinparis.com'
    method: GET
    expectStatus: 200

    - id: comfortablefood-com
    name: comfortablefood.com
    url: 'https://comfortablefood.com'
    method: GET
    expectStatus: 200

    - id: thehomesihavemade-com
    name: thehomesihavemade.com
    url: 'https://thehomesihavemade.com'
    method: GET
    expectStatus: 200

    - id: wholekitchensink-com
    name: wholekitchensink.com
    url: 'https://www.wholekitchensink.com'
    method: GET
    expectStatus: 200  

    - id: Momcrieff-com
    name: momcrieff.com
    url: 'https://momcrieff.com'
    method: GET
    expectStatus: 200

    - id: Momcrieff-com    
    name: momcrieff.com
    url: 'https://momcrieff.com'
    method: GET
    expectStatus: 200
